# Generated by Django 5.1.1 on 2024-10-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elecproducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
